# This machine, and the assembly that builds it. One host, so the aspect
# registries are imported wholesale with nothing to gate against.
{ config, inputs, ... }:

{
  flake.modules.nixos.host =
    { ... }:
    {
      networking.hostName = "goosenest";
      # The NixOS version this machine was first installed on — never bump it.
      system.stateVersion = "26.05";
    };

  flake.nixosConfigurations.goosenest = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";

    specialArgs = {
      inherit inputs;
      username = "juicygoose007";
    };

    modules = [
      # Generated by nixos-generate-config and restored per-machine by
      # install.sh, which is why it sits at the repo root.
      ../hardware-configuration.nix
    ]
    ++ builtins.attrValues config.flake.modules.nixos
    ++ [
      inputs.home-manager.nixosModules.home-manager
      {
        home-manager.useGlobalPkgs = true;
        home-manager.useUserPackages = true;
        home-manager.users.juicygoose007.imports =
          builtins.attrValues config.flake.modules.homeManager;
        home-manager.extraSpecialArgs = {
          inherit inputs;
          username = "juicygoose007";
        };
      }
    ];
  };
}
